home/urls.py
from django.urls import path,include
from .import views

app_name = "home"
urlpatterns = [
    path('', views.index, name="index"),
    path('women-bleeders/', views.womenBleeders, name='womenBleeders'),
    path('treatments/', views.treatments, name='treatment'),
    path('inhibitors/', views.inhibitors, name='inhibitors'),
    path('treatments-details/<str:slug>/<str:category>/', views.treatmentsDetails, name='treatments_slug'),
    path('contact-us',views.contactUs, name="contactUs"),
    path('real-stories/<int:pk>/',views.realstories, name="realStories"),
]

hsnc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('home.urls')),
    path('hemophilia/', include('hemophilia.urls')),
    path('vWd/', include('vwd.urls')),
    # path('women-bleeders/', include('home.urls')),
    # path('treatments/', include('home.urls')),
    # path('inhibitors/', include('home.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vwd/urls.py
from django.urls import path
from .import views

app_name = "vwd"
urlpatterns = [
    path('', views.vWd, name="vWd"),
    path('<str:slug>/', views.vWd_more, name="vWd_slug"),
]

home/models.py
from enum import auto
from django.db import models
from django.db.models.base import Model
from django.db.models.expressions import F
from django.urls import reverse
from tinymce.models import HTMLField


# Create your models here.
class hsnc(models.Model):
    category = models.CharField(max_length=50,default="")
    slug = models.SlugField(max_length=50)
    class Meta:
        verbose_name_plural ="HSNC _Data"
    def __str__(self):
        return self.category

    def get_absolute_url(self):
        return reverse("hemophilia:hemophilia", args=[self.slug])

class posts(models.Model):
    id = models.AutoField(primary_key=True)
    category = models.ForeignKey(hsnc, on_delete=models.CASCADE)
    title = models.CharField(max_length=100,default="")
    content = HTMLField()
    slug = models.SlugField(max_length=50)
    image_1 = models.FileField(upload_to="images",null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("hemophilia:about", args=[self.slug])

class TreatMents(models.Model):
    title = models.CharField(max_length=100, null=False)
    content = HTMLField(default="")

    slug = models.SlugField(max_length=50, default="")
    image_1 = models.FileField(upload_to="images",null=True, blank=True)
    image_2 = models.FileField(upload_to="images",null=True, blank=True)
    image_3 = models.FileField(upload_to="images",null=True, blank=True)

    class Meta:
        verbose_name_plural ="Treatments"
    def __str__(self):
        return self.title

class ContactUs(models.Model):
    name = models.CharField(max_length=100, null=False,blank=False)
    email = models.EmailField(blank=False,null=False,max_length=254)
    mo_no = models.IntegerField(blank=True, null=True)
    query = models.TextField(blank=False,null=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural ="Contact Us"


class RealStories(models.Model):
    heading = models.CharField(max_length=150,blank=False, null=False,default="Real Story")
    description = models.TextField(blank=False,null=False)
    image = models.FileField(upload_to="realstory", null=True, blank=True)

    def __str__(self):
        return self.heading
    
    class Meta:
        verbose_name_plural ="Real Stories"

class Slider(models.Model):
    heading = models.CharField(max_length=150,blank=False, null=False,default=" ")
    description = models.TextField(blank=False,null=False)
    image = models.FileField(upload_to="slider", null=True, blank=True)

    def __str__(self):
        return self.heading
    
    class Meta:
        verbose_name_plural ="Slider"

home/views.py
from django.db import reset_queries
from django.http.response import HttpResponse
from django.shortcuts import render
from .models import hsnc, TreatMents, ContactUs,RealStories, Slider, posts
from hemophilia.models import Hemophilia
# Create your views here.


def categories(request):
    return{'categories':hsnc.objects.all()}

def index(request):
    status =True
    qs = RealStories.objects.all()
    slider = Slider.objects.all()
    context = {'qs':qs,'home':status, 'slider':slider}
    return render(request, 'home/index.html', context)

def inhibitors(request):
    # qs = Hemophilia.objects.all().exclude(slug=slug)
    query = posts.objects.filter(slug='inhibitors')
    status = True
    context = {'query':query,'bd':status}
    return render(request, 'hemophilia/hemophilia.html',context)

def treatments(request):
    category = hsnc.objects.get(slug="treatments")
    qs = posts.objects.all().filter(category=category)
    status =True
    context = {'qs':qs, 'bd':status}
    return render(request, 'home/treatments.html', context)

def treatmentsDetails(request,slug,category):
    post_category = hsnc.objects.get(category=category)
    qs = posts.objects.filter(category=post_category).exclude(slug=slug)
    query = posts.objects.filter(slug=slug)
    # qs = posts.objects.all().exclude(slug=slug)
    # query = posts.objects.filter(slug=slug)
    status = True
    context = {'query':query,'qs':qs,'bd':status}
    return render(request, 'home/treatments.html', context)

def womenBleeders(request):
    query = posts.objects.filter(slug='women-with-bleeding-disorder')

    status = True
    context = {'bd':status,'query':query}
    return render(request, 'hemophilia/womenBleeders.html', context)

def contactUs(request):
    status = True

    if request.method =='POST':
            name = request.POST['name']
            email = request.POST['email']
            mo_no = request.POST['contact_no']
            msg = request.POST['content']
            msgData = ContactUs()
            msgData.name = name
            msgData.email = email
            msgData.mo_no = mo_no
            msgData.query = msg
            msgData.save()
            return render(request, 'home/contactUs.html')
    context = {'status':status}
    return render(request, 'home/contactUs.html',context)


def realstories(request, pk):
    qs = RealStories.objects.all().filter(pk=pk)
    context = {'qs':qs}
    return render(request, 'home/realstories.html', context)

templates/home/about.html
{% extends 'base.html' %}
{% load static %}

{% block container_1 %}

{% for data in  query %}
<div class="con_1_row_1">
    <h3 class="heading">{{data.title_1}}</h3><br>
    <p>{{data.para_1}}</p><br>
    <h4 class="heading">{{data.title_2}}</h4><br>
    <p>{{data.para_2}}</p><br>
    <h4 class="heading">{{data.title_3}}</h4><br>
    <p>{{data.para_3}}</p><br>

    </div>

{% endfor %}

{% endblock container_1 %}

<script src="{% static 'js/script.js' %}"></script>

templates/home/contactUs.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="container mt-3">
  {% comment %}
  <div class="message-icon">
    <i class="far fa-comment-alt"></i>
  </div>
  {% endcomment %}
  <div class="row">

    <div class="col-12 min-ht-90">
        <div class="contact-us d-flex-center-col">
            <h2>Contact Us</h2>
            <div class="underline bg-primary mt-1"></div>
         </div>
    </div>


    <div class="col-7 col-sm-12 min-ht-90 d-flex j-con-center">
        <form
          action="/contact-us"
          class="contact-form mt-3 shadow"
          method="POST"
        >
          {% csrf_token %}

          <div class="form-section">
            <label for="name">Name</label>
            <input type="text" name="name" required placeholder="Full Name" />
          </div>

          <div class="form-section">
            <label for="email">Email</label>
            <input
              type="email"
              name="email"
              required
              placeholder="Enter Your Email Id"
            />
          </div>

          <div class="form-section">
            <label for="contact-no">Contact No</label>
            <input
              type="tel"
              name="contact_no"
              required
              placeholder="Enter Your Mobile No"
            />
          </div>

          <textarea
            placeholder="Enter Your Message Here"
            name="content"
            id="content"
            cols="30"
            rows="7"
          ></textarea>
          <button type="submit" class="btn m-auto">Submit</button>
        </form>
      </div>
    <div class="col-5 col-sm-12">
      <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3721.1676925597835!2d79.07799351915718!3d21.145723735865886!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bd4c0ecb66dd101%3A0xa41f3eac3096a4f9!2sYMCA%20Complex%2C%20NH%206%2C%20Civil%20Lines%2C%20Nagpur%2C%20Maharashtra%20440001!5e0!3m2!1sen!2sin!4v1647515090227!5m2!1sen!2sin"
         width="600"
        height="450" 
        style="border: 0"
        allowfullscreen=""
        loading="lazy"
        class="mt-3 g-map"
      ></iframe>
    </div>
  </div>
</div>
{% endblock content %}

templates/home/history.html
{% extends 'base.html' %}
{% load static %}

{% block container_1 %}
<h4><a href="/">Home</a>/Bleeding Dissorders/<a href="#">{{data.title_1}}</a></h4>

{% for data in  query %}
<div class="con_1_row_1">
    <h3 class="heading">{{data.title_1}}</h3>
    <p>{{data.para_1}}</p>
    <h4 class="heading">{{data.title_2}}</h4>
    <p>{{data.para_2}}</p>
    <h4 class="heading">{{data.title_3}}</h4>
    <p>{{data.para_3}}</p>
    </div>

{% endfor %}

{% endblock container_1 %}
<script src="{% static 'js/script.js' %}"></script>

templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
  <!-- ----------------- Slider row------------ -->
  <div class="row">

    <div class="col-12 p1">
      <div class="slider-container">
        <div class="time-line"></div>

        {% for slides in slider %}
        <div class="slide" onMouseout="runShow()" onMouseover="stopShow()">

          <img class="slider_img" src="/media/{{slides.image}}" alt="" />
          <div class="text">
            {% comment %} <h4 class=" w-50">{{slides.heading}}</h4> {% endcomment %}
            <p class="text-left">
              {{slides.description}}
            </p>
          </div>
        </div>
        {% endfor %}

        <button class="arrow left-arrow" id="left">
          <i class="fas fa-chevron-left"></i>
        </button>
        <button class="arrow right-arrow" id="right">
          <i class="fas fa-chevron-right"></i>
        </button>
      </div>

    </div>
  </div>
</div>


<div class="container mt-5 bg-white" id="about_us"> {% comment "" %}about section {% endcomment %}
  <div class="row">
    <!-- <div class="col-12 p1 animate  fade-in-bottom">
        <h1 class="spacing-1 clr-dark p3  uppercase">Hemophilia Society Nagpur</h1>
    </div> -->
  </div>

  <div class="row grid-row-gap">
    <div class="col-12 col-sm-12 border-radius-1 animate fade-in-bottom">
      <h2 class="m-auto clr-primary p1 h2 animate fade-in-bottom">Our Vision</h2>
        <div class="vision mt-4 d-flex j-con-center animate fade-in-bottom">
          <img src="{% static 'imgs/vision1.png' %}" alt="" class="w-50 w-sm-100">

          <ul class="text-left p3 c-white w-50 w-sm-100">
            <li>Reaching out People with Hemophilia (PwH) and other Related Inherited Bleeding Disorders.</li>
            <li>Providing Diagnosis, Treatment and Rehabilitation services.</li>
            <li>Training of Medical & Para Medical Professionals.</li>
            <li>Public / Media Awareness.</li>
            <li>Resource Mobilization to Sustain Welfare Activities.</li>
            <li>Advocacy with Government for its Involvement and Support.</li>
            <li>Networking with Like-minded organizations (like Disability, HIV/ AIDS, Blood safety…)</li>
          </ul>
        </div>

    </div>
  
    <div class="col-12 col-sm-12 mt-4 animate fade-in mt-4 our-service">
      <h2 class="mt-3 h2 text-center c-white spacing-1 animate fade-in-bottom">Our Services</h2>
      <div class="d-grid-autofit mt-4 text-left">
        <div class="card-service p2 d-flex animate fade-in-bottom">
          <div class="d-flex-col-center p1 gap-1">
            <div class="service-icon m-auto w-25"><img src="{% static 'imgs/information.png' %}" alt=""></div>

            <h3 class="mt-2">Information on Hemophilia</h3>
            <div class="service-text text-muted mt-2">We provide complete information on Hemophilia and its associated condition.
              Beneficiaries can avail information to channelize their life style towards healthy outcome</div>
          </div>
        </div>
        <div class="card-service p2 d-flex animate fade-in-bottom">
          <div class="d-flex-col-center p1">
            <div class="service-icon w-25 m-auto"><img src="{% static 'imgs/patientcare.png' %}" alt=""> </div>
            <h3 class="mt-2">Patient Care Services</h3>

            <div class="service-text text-muted mt-2">Out-patient and in-patient services for people with hemophilia. We are also
              empanelled with State Government to procure and distribute factors for patients</div>
          </div>
        </div>
        <div class="card-service p2 d-flex animate fade-in-bottom">
          <div class="d-flex-col-center p1">
            <div class="service-icon m-auto w-25"><img src="{% static 'imgs/counselling.png' %}" alt=""> </div>


            <h3 class="mt-2">Counselling</h3>
            <div class="service-text text-muted mt-2">We offer psychosocial and counselling services for the family to overcome the
              common stigma associated with hemophilia.</div>
          </div>
        </div>
        <div class="card-service p2 d-flex animate fade-in-bottom">
          <div class="d-flex-col-center p1">
            <div class="service-icon m-auto w-25"><img src="{% static 'imgs/physiotherapy.png' %}" alt=""> </div>

            <h3 class="mt-2">Physiotherapy</h3>
            <div class="service-text  mt-2">Disability is one of the complications of uncontrolled hemophilia. We help the
              disabled to strengthen their joints and muscle to overcome repeated bleeding.</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% comment %} Real life story section {% endcomment %}


<div class="container ht-mn-100 mt-5 shadow-light  animate fade-in">
  <div class="row">
    <div class="col-12 mt-5">
      <h1 class="real-life-title h2 p1 clr-primary animate tracking-in-expand-fwd uppercase">Real Life Stories</h1>
      <!-- <div class="underline bg-primary animate fade-in m-auto"></div> -->

    </div>
  

    <div class="col-12 real-story animate fade-in-bottom">
      {% for data in qs %}
      <article class="card-story mt-3">
        <img src="/media/{{data.image}}" alt="" class="m-auto" alt="story1" />
        <h4 class="p1">{{data.heading}}</h4>
        <p class="title text-muted">Product designer</p>
        <p class="story-desc text-muted mt-4">
          {{data.description|truncatechars:100}}
          <a href="real-stories/{{data.pk}}" class="clr-blue card-story-more" area-label="read more">Read More</a>
        </p>

        <div class="quote-icon">
          <i class="fas fa-quote-right"></i>
        </div>

      </article>



      {% endfor %}
      <button class="btn prev-btn" id="prev-btn">
        <i class="fas fa-chevron-left"></i>
      </button>
      <!-- next button -->
      <button class="btn next-btn" id="next-btn">
        <i class="fas fa-chevron-right"></i>
      </button>
    </div>

  </div>
</div>

<div class="container mt-1 ht-mn-100 animate fade-in-bottom p1" id="news_events">
  <div class="row mt-3">
    <div class="col-12 mt-5">
      <h1 class="heading h2 clr-dark">News & Events</h1>
      <div class="underline bg-primary m-auto"></div>
    </div>
    <div class="col-6 col-sm-12 mt-2 p1">
      <div class="">
        <h3 class="bg-pink c-white p1 border-radius-1 fw-400">News</h3>
        <div class="d-flex mt-2 p1 gap-1 news text-left  ">
              <img src="{% static 'imgs/newspaper.svg' %}" alt="" class="w-25">
              <div class="">
                <b class="">Title</b>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, ex!</p>
            </div>
        </div>
        <div class="d-flex mt-2 p1 gap-1 news text-left  ">
              <img src="{% static 'imgs/newspaper.svg' %}" alt="" class="w-25">
              <div class="">
                <b>Title</b>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, ex!</p>
            </div>
        </div>
        <div class="d-flex mt-2 p1 gap-1 news text-left  ">
              <img src="{% static 'imgs/newspaper.svg' %}" alt="" class="w-25">
              <div class="">
                <b>Title</b>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, ex!</p>
            </div>
        </div>
      </div>
    </div>
    <div class="col-6 col-sm-12 mt-2 p1">
     <div class="">
       <h3 class="bg-pink c-white p1 border-radius-1 fw-400">Upcoming Events - 2022</h3>
       
       <div class="d-flex mt-2 p1 gap-1 news text-left  ">
        <img src="{% static 'imgs/calender.svg' %}" alt="" class="w-25">
        <div class="">
          <p>Month</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, ex!</p>
      </div>
  </div>
  <div class="d-flex mt-2 p1 gap-1 news text-left ">
        <img src="{% static 'imgs/calender.svg' %}" alt="" class="w-25">
        <div class="">
          <p>Title</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, ex!</p>
      </div>
  </div>
  <div class="d-flex mt-2 p1 gap-1 news text-left  ">
        <img src="{% static 'imgs/calender.svg' %}" alt="" class="w-25">
        <div class="">
          <p>Title</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, ex!</p>
      </div>
  </div>
     </div>
    </div>
  </div>
</div>
{% endblock content%}

{% block js %}
<script src="{% static 'js/script_2.js' %}"></script>

{% endblock js %}

templates/home/realstories.html
{% extends 'base.html' %}



{% block content %}
{% for data in qs  %}
<div class="container p1">


<div class="row">
<div class="col-8 col-sm-12 p1 ht-100 mt-2 text-left">
<h2> {{data.heading}}</h2>
<p class="subheading"> {{data.description}}</p>
</div>
<div class="col-4 col-sm-12 mt-2">
<img src="/media/{{data.image}}" class="card_img" loading="lazy">

</div>
</div>

{% endfor %}
</div>


{% endblock content %}

templates/home/treatments.html
{% extends 'base.html' %}
{% load static %}

{% block content%}


{% for data in query %}
<div class="container p3">
    <div class="row">
        <div class="col-12">
            <div class="current_url text-left">
                <p class="clr-blue"><a href="/"class="clr-blue"><i class="fa fa-home" aria-hidden="true"></i>&nbsp;<span>&nbsp;/&nbsp;</span> </a> Bleeding Dissorders <span>&nbsp;/&nbsp;</span>
                    <a href="#"class="clr-blue"> {{data.title}}</a>
                </p>
            </div>
        </div>
        <div class="col-12">
            <div class="text-left">
                <h2 class="heading clr-dark mt-1">{{data.title}}</h2>

            </div>
        </div>
        <div class="col-12 mt-2 text-muted l-height-2">
            <p class="text-left  p1 ">{{data.content|safe}}</p>

        </div>
        <div class="col-4 col-sm-12">
            <div class="mt-2">
                {% if data.image_1 %}
                <div class="">
                    <img src="/media/{{data.image_1}}" class="card_img" loading="lazy">
                </div>
                {% endif %}
               
            </div>
        </div>
        {% if data.title %}
        <div class="col-12">
            <div class="mt-2 text-left">
                <h2 class="heading ml-1">{{data.title_2}}</h2>
            </div>
        </div>
        {% endif %}
       
    </div>
    <!-- <div class="col-12 mt-4">
        <h3>Related Article</h3>
    </div>
    <div class="col-12">
        <div class="underline-dark"></div>
    </div> -->
</div>
{% comment %} </div> {% endcomment %}
{% endfor %}
<div class="row">
    <div class="col-12 text-left p3">
        <strong class="">Disclaimer:</strong><p class="text-muted mt-1"> This website is for information purposes only and provides an overview of 
            the subject matter covered. It is not a substitute for professional medical advice, diagnosis or treatment.
             Always consult your haemophilia centre for specific advice on your healthcare concerns. The information on this website is subject to change without notice. </p>
    </div>
</div>

{% if qs %}
<div class="container mt-4 p1">
    <div class="row grid-gap1">
        <div class="col-12 mb-2">
            {% if query %}
                 <h3>Related Articles</h3>
            {% else %}
                <h3>Treatments</h3>
            {% endif %}
            <div class="underline-dark m-auto"></div>
            </div>
    {% for data in qs %}
        <div class="col-4 col-sm-12 d-flex-center-col shadow">

            <div class="card_more d-flex-col-center">
                <div class="card-img">
                    {% if data.image_1 %}
                    <img src="/media/{{data.image_1}}" class="card_img">
            
                    {% else %}
                    <img src="{% static 'imgs/logoHSNC.png'%}" class="card_img">
                    {% endif %}
                </div>
                <div class="card-text p2">
                    <h4>{{data.title}}</h4>
                    <p class="text-left subheading mt-1">{{data.content|truncatechars_html:100|safe}}</p>
                    <button class="btn btn-red mt-1 c-white flex-end"><a href="{% url 'home:treatments_slug' data.slug data.category %}">Read More</a></button>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endif %}
{% endblock content %}


<script src="{% static 'js/script.js' %}"></script>