hemophilia/urls.py
from django.urls import path
from .import views

app_name = 'hemophilia'

urlpatterns = [
    path('', views.hemophilia, name="hemophilia"),
    path('about/<str:slug>/<str:category>/', views.about, name="about"),
]

hsnc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('home.urls')),
    path('hemophilia/', include('hemophilia.urls')),
    path('vWd/', include('vwd.urls')),
    # path('women-bleeders/', include('home.urls')),
    # path('treatments/', include('home.urls')),
    # path('inhibitors/', include('home.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vwd/urls.py
from django.urls import path
from .import views

app_name = "vwd"
urlpatterns = [
    path('', views.vWd, name="vWd"),
    path('<str:slug>/', views.vWd_more, name="vWd_slug"),
]

vwd/models.py
from django.db import models
from tinymce.models import HTMLField

# Create your models here.


class VWD(models.Model):
    title= models.CharField(max_length=100, null=False)
    content =HTMLField(default="")
    slug = models.SlugField(default="")
    image_1 = models.FileField(upload_to="images",null=True, blank=True)
    image_2 = models.FileField(upload_to="images",null=True, blank=True)
    image_3 = models.FileField(upload_to="images",null=True, blank=True)
    # treatment = models.OneToOneField(Treatment,)

    def __str__(self):
        return self.title
    class Meta:
        verbose_name_plural ="von Willebrand Disease"

vwd/views.py
from django.shortcuts import render

from home.models import hsnc, posts
from .models import VWD

# Create your views here.
def vWd(request):
    str = 'von-willebrand-disease'
    category = hsnc.objects.get(slug=str)
    qs = posts.objects.all().filter(category=category).exclude(slug='von-willebrand-disease')
    query = posts.objects.all().filter(category=category).filter(slug='von-willebrand-disease')
    status = True
    context = {'query':query,'qs':qs,'bd':status}
    return render(request,'vWd/index.html',context)



def vWd_more(request, slug):
    qs = VWD.objects.all().exclude(slug = slug)
    query = VWD.objects.filter(slug = slug)
    status = True
    context = {'query':query,'qs':qs,'bd':status}
    return render(request,'vWd/index.html',context)

templates/vWd/index.html
{% extends 'base.html' %}
{% load static %}

{% block content%}


{% for data in query %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="current_url text-left">
                <p class="clr-blue p1 ml-1"><a href="/"class="clr-blue"><i class="fa fa-home" aria-hidden="true"></i>&nbsp;<span>&nbsp;/&nbsp;</span> </a> Bleeding Dissorders <span>&nbsp;/&nbsp;</span>
                    <a href="#"class="clr-blue"> {{data.title}}</a>
                </p>
            </div>
        </div>
        <div class="col-12 p3">
            <div class="text-left">
                <h1 class="heading clr-dark mt-1">{{data.title}}</h1>

            </div>
            <div class="underline bg-primary"></div>

        </div>
        <div class="col-12 col-sm-12 mt-2">
            <div class="m-auto w-25 w-sm-100">
                {% if data.image_1 %}
                <div class="">
                    <img src="/media/{{data.image_1}}" class="card_img" loading="lazy">
                </div>
                {% endif %}
               
            </div>
        </div>
        <div class="col-12 col-sm-12 mt-1 p3">

             <div class="text-muted l-height-2 font-serif">
         {{data.content|safe}}</div>

        </div>
        
    
    </div>
</div>
{% comment %} </div> {% endcomment %}
{% endfor %}


<hr>
{% if qs %}
<div class="container mt-4 p1">
    <div class="row grid-gap1">
        <div class="col-12 mb-2">
            <h2 class="clr-dark mb-1">Related Articles</h2>
            <div class="underline-dark m-auto"></div>

        </div>
    
        {% for data in qs %}
        <div class="col-4 col-sm-12 d-flex-center-col shadow">

            <div class="card_more d-flex-col-center">
                <div class="card-img">
                    {% if data.image_1 %}
                    <img src="/media/{{data.image_1}}" class="card_img">
            
                    {% else %}
                    <img src="{% static 'imgs/logoHSNC.png'%}" class="card_img">
                    {% comment %} <img src="{{ data.image.url }}" class="card_img"> {% endcomment %}
                    {% endif %}
                </div>
                <div class="card-text p2 d-flex-center-col">
                    <h4>{{data.title}}</h4>
                    <p class="text-left subheading mt-1">{{data.content|truncatechars_html:150|safe}}</p>
                    <button class="btn btn-red mt-2 c-white"><a href="{% url 'hemophilia:about' data.slug data.category %}">Read More</a></button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>


</div>
{% endif %}
{% endblock content %}


<script src="{% static 'js/script.js' %}"></script>